"""create session tables

Revision ID: 0d07cdd64f6b
Revises: c1236465921b
Create Date: 2026-09-24 07:32:05.921292

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0d07cdd64f6b"
down_revision: str | None = "c1236465921b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("child_id", sa.UUID(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("device_info", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("mood_before", sa.String(), nullable=True),
        sa.Column("mood_after", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sessions_child_id"), "sessions", ["child_id"], unique=False)
    op.create_table(
        "week1_progress",
        sa.Column("child_id", sa.UUID(), nullable=False),
        sa.Column("day_index", sa.Integer(), nullable=False),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("day_index BETWEEN 1 AND 7", name="ck_week1_progress_day_index"),
        sa.PrimaryKeyConstraint("child_id", "day_index"),
    )
    op.create_table(
        "activity_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("activity", sa.String(), nullable=False),
        sa.Column("activity_version", sa.String(), nullable=False),
        sa.Column("day_index", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('started', 'completed', 'skipped', 'quit')", name="ck_activity_runs_status"
        ),
        sa.CheckConstraint(
            "day_index IS NULL OR day_index BETWEEN 1 AND 7", name="ck_activity_runs_day_index"
        ),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_activity_runs_activity"), "activity_runs", ["activity"], unique=False)
    op.create_index(
        op.f("ix_activity_runs_session_id"), "activity_runs", ["session_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_activity_runs_session_id"), table_name="activity_runs")
    op.drop_index(op.f("ix_activity_runs_activity"), table_name="activity_runs")
    op.drop_table("activity_runs")
    op.drop_table("week1_progress")
    op.drop_index(op.f("ix_sessions_child_id"), table_name="sessions")
    op.drop_table("sessions")
    # ### end Alembic commands ###
