"""create safety_flags table

Revision ID: 313935531bb7
Revises: c9dae9fdbc8f
Create Date: 2026-09-28 11:57:25.360262

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "313935531bb7"
down_revision: str | None = "c9dae9fdbc8f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "safety_flags",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("child_id", sa.UUID(), nullable=False),
        sa.Column("rule", sa.String(), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("reviewer_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('open', 'reviewed', 'referred', 'dismissed')", name="ck_safety_flags_status"
        ),
        sa.ForeignKeyConstraint(["child_id"], ["children.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_safety_flags_child_id"), "safety_flags", ["child_id"], unique=False)
    op.create_index(op.f("ix_safety_flags_rule"), "safety_flags", ["rule"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_safety_flags_rule"), table_name="safety_flags")
    op.drop_index(op.f("ix_safety_flags_child_id"), table_name="safety_flags")
    op.drop_table("safety_flags")
    # ### end Alembic commands ###
