"""create media_objects table

Revision ID: 35d78e387717
Revises: 313935531bb7
Create Date: 2026-09-28 12:13:33.287549

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "35d78e387717"
down_revision: str | None = "313935531bb7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media_objects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("child_id", sa.UUID(), nullable=False),
        sa.Column("activity_run_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("storage_key", sa.String(), nullable=False),
        sa.Column("consent_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('audio', 'video')", name="ck_media_objects_kind"),
        sa.ForeignKeyConstraint(["activity_run_id"], ["activity_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["child_id"], ["children.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["consent_id"],
            ["consents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_index(
        op.f("ix_media_objects_activity_run_id"), "media_objects", ["activity_run_id"], unique=False
    )
    op.create_index(op.f("ix_media_objects_child_id"), "media_objects", ["child_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_media_objects_child_id"), table_name="media_objects")
    op.drop_index(op.f("ix_media_objects_activity_run_id"), table_name="media_objects")
    op.drop_table("media_objects")
    # ### end Alembic commands ###
