"""add one-active-plan-per-child constraint

Revision ID: 6494fb782e48
Revises: 0d07cdd64f6b
Create Date: 2026-09-28 10:52:11.391239

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "6494fb782e48"
down_revision: str | None = "0d07cdd64f6b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_plans_one_active_per_child",
        "plans",
        ["child_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_plans_one_active_per_child",
        table_name="plans",
        postgresql_where=sa.text("status = 'active'"),
    )
    # ### end Alembic commands ###
