"""create identity tables

Revision ID: c9dae9fdbc8f
Revises: 6494fb782e48
Create Date: 2026-09-28 10:30:24.579967

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "c9dae9fdbc8f"
down_revision: str | None = "6494fb782e48"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guardians",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("relationship", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("locale", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_guardians_phone"), "guardians", ["phone"], unique=True)
    op.create_table(
        "schools",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("area", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "children",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("guardian_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("gender", sa.String(), nullable=True),
        sa.Column("area", sa.String(), nullable=False),
        sa.Column("schooling", sa.String(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=True),
        sa.Column("grade", sa.String(), nullable=True),
        sa.Column("home_languages", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("avatar", sa.String(), nullable=True),
        sa.Column(
            "onboarded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "schooling != 'school' OR school_id IS NOT NULL",
            name="ck_children_school_requires_school_id",
        ),
        sa.CheckConstraint("schooling IN ('school', 'home_school')", name="ck_children_schooling"),
        sa.ForeignKeyConstraint(
            ["guardian_id"],
            ["guardians.id"],
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_children_guardian_id"), "children", ["guardian_id"], unique=False)
    op.create_table(
        "consents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("child_id", sa.UUID(), nullable=False),
        sa.Column("guardian_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("audio", sa.Boolean(), nullable=False),
        sa.Column("video", sa.Boolean(), nullable=False),
        sa.Column("teacher_share", sa.Boolean(), nullable=False),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["child_id"], ["children.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["guardian_id"],
            ["guardians.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_consents_child_id"), "consents", ["child_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_consents_child_id"), table_name="consents")
    op.drop_table("consents")
    op.drop_index(op.f("ix_children_guardian_id"), table_name="children")
    op.drop_table("children")
    op.drop_table("schools")
    op.drop_index(op.f("ix_guardians_phone"), table_name="guardians")
    op.drop_table("guardians")
    # ### end Alembic commands ###
