"""create signal_events table

Revision ID: dcd9590ddc17
Revises:
Create Date: 2026-09-24 11:22:32.068909

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "dcd9590ddc17"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "signal_events",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("child_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("activity_run_id", sa.UUID(), nullable=False),
        sa.Column("activity", sa.String(), nullable=False),
        sa.Column("activity_version", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("ts_client", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "ts_server", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(op.f("ix_signal_events_activity"), "signal_events", ["activity"], unique=False)
    op.create_index(
        op.f("ix_signal_events_activity_run_id"), "signal_events", ["activity_run_id"], unique=False
    )
    op.create_index(op.f("ix_signal_events_child_id"), "signal_events", ["child_id"], unique=False)
    op.create_index(
        op.f("ix_signal_events_session_id"), "signal_events", ["session_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_signal_events_session_id"), table_name="signal_events")
    op.drop_index(op.f("ix_signal_events_child_id"), table_name="signal_events")
    op.drop_index(op.f("ix_signal_events_activity_run_id"), table_name="signal_events")
    op.drop_index(op.f("ix_signal_events_activity"), table_name="signal_events")
    op.drop_table("signal_events")
    # ### end Alembic commands ###
